// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu2eJGxB8-Q8c1LOQ3RLACrat3Mk5Bf-o',
    appId: '1:67992803860:web:153209b2e5a8f92d226501',
    messagingSenderId: '67992803860',
    projectId: 'banua-insight',
    authDomain: 'banua-insight.firebaseapp.com',
    storageBucket: 'banua-insight.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEwXLc5Q3w38pRoJwAz0GS1y7C4LyIf7U',
    appId: '1:67992803860:android:6868dccc057c1b96226501',
    messagingSenderId: '67992803860',
    projectId: 'banua-insight',
    storageBucket: 'banua-insight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fxBlg51GjViPcQjw1W-axQ2Rt0EBlLw',
    appId: '1:67992803860:ios:ba9d3b1eeb90a2cd226501',
    messagingSenderId: '67992803860',
    projectId: 'banua-insight',
    storageBucket: 'banua-insight.firebasestorage.app',
    iosBundleId: 'com.example.banuainsightProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fxBlg51GjViPcQjw1W-axQ2Rt0EBlLw',
    appId: '1:67992803860:ios:ba9d3b1eeb90a2cd226501',
    messagingSenderId: '67992803860',
    projectId: 'banua-insight',
    storageBucket: 'banua-insight.firebasestorage.app',
    iosBundleId: 'com.example.banuainsightProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu2eJGxB8-Q8c1LOQ3RLACrat3Mk5Bf-o',
    appId: '1:67992803860:web:825e71685f9a8506226501',
    messagingSenderId: '67992803860',
    projectId: 'banua-insight',
    authDomain: 'banua-insight.firebaseapp.com',
    storageBucket: 'banua-insight.firebasestorage.app',
  );
}
